### ISSUE TITLE
It's a little bug, this text "Create new environment" is not a property 

### ISSUE THREAD

**Issue by joelcamus** [postwoman-io/postwoman#1076] opened 2020-08-15 10:58 UTC
It's a little bug, this text "Create new environment" is not a property.

It's the same that #1074 

![imagen](https://user-images.githubusercontent.com/8535654/90310996-eac01780-def6-11ea-8206-39b2b8f30c26.png)

**Comment by liyasthomas** [comment] 2020-08-15 11:19
Duplicate of #1074 
Don't spam.

**Closed by liyasthomas** 2020-08-15 11:19 UTC
